name: Build PlotSquaredLite
on:
  push:
    paths:
      - "Lite/**"
      - ".github/workflows/build-lite.yml"
  pull_request:
    paths:
      - "Lite/**"
      - ".github/workflows/build-lite.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21
      - name: Build
        run: ./gradlew -p Lite build
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: PlotSquaredLite
          path: Lite/build/libs/*.jar
